apiVersion: v1

kind: Service
metadata:
  name: blue-green-service
  labels:
    env: dev
    apllication: web-app

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009
  selector:
    application: web-app
